# Generated by Django 5.2.6 on 2026-06-25 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100)),
                ('responsavel', models.CharField(max_length=100)),
                ('setor', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('SERVIDOR', 'servidor'), ('NOTEBOOK', 'notebook'), ('ROTEADOR', 'roteador'), ('APLICACAO_WEB', 'aplicacao web')], max_length=20)),
                ('dados_json', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Ativo',
                'verbose_name_plural': 'Ativos',
            },
        ),
        migrations.CreateModel(
            name='Vulnerabilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('severidade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], max_length=20)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_TRATAMENTO', 'Em Tratamento'), ('CORRIGIDA', 'Corrigida'), ('ACEITA', 'Aceita com Risco')], max_length=20)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilidades', to='ativos.ativo')),
            ],
            options={
                'verbose_name': 'Vulnerabilidade',
                'verbose_name_plural': 'Vulnerabilidades',
            },
        ),
    ]
