# Generated by Django 5.2.6 on 2026-06-30 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vulnerabilidades',
            new_name='Vulnerabilidade',
        ),
    ]
